#!/usr/bin/python2.3
# arch-tag: program to import full Debian source package
# Copyright (C) 2003 John Goerzen
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
#

import os, sys
from tbppy import tbpimport

def printhelp():
    print """Usage:
%s dscname

Where:
  orig-name is the name of a dsc file to import""" % sys.argv[0]

def syntax():
    printhelp()
    sys.exit(1)

if len(sys.argv) != 2:
    syntax()

dscname = sys.argv[1]
tbpimport.importdsc(dscname)
