#!/bin/bash
# -*- Mode: shell-script; -*-
# arch-tag: main entry point
# Copyright (C) 2003 John Goerzen
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA
#
# Depends: awk, bash, sed, dpkg-dev, devscripts
# Programs: tail, tla, grep

set -e

getlastupstream() {
  tla merges `tla tree-version` | grep $1 | tail -n 1 | awk '{ print $2 }'
}

getupstreamtree() {
  cat debian/tla-upstream
}

getupstreamrev() {
  getlastupstream `getupstreamtree`
}

getdebianver() {
  dpkg-parsechangelog | sed -n 's/^Version: //p'
}

getupstreamver() {
  getdebianver | sed 's/-[^-]\+$//'
}

getpackage() {
  dpkg-parsechangelog | sed -n 's/^Source: //p'
}

echo -n " *** tla-buildpackage for "
getdebianver

UPSTREAMREV=`getupstreamrev`
WCDIR=`pwd`
WCDIRNAME=$(basename `pwd`)

cd ..
ORIGDIRNAME=$(WCDIRNAME).orig
ORIGDIR=`pwd`/$(ORIGDIRNAME)

echo " *** Building $ORIGDIRNAME from $UPSTREAMREV"
tla get $UPSTREAMREV $ORIGDIRNAME

TARNAME=`getpackage`_`getupstreamver`.orig.tar.gz
echo " *** Building $TARNAME"

tla inventory -s $ORIGDIRNAME | tar -cSpf - -T- | gzip -9 > $TARNAME

rm -r $ORIGDIRNAME
cd "$WCDIR"

echo " *** Running build program"
debuild -i '\+\+pristine-trees' -i ',,*' "$@"

rm -r $(ORIGDIR) &> /dev/null || true
tla get $UPSTREAMREV

TMPDIR=/tmp/tla-buildpackage.$$
mkdir -m 0700 $TMPDIR

rm -r $TMPDIR