Document: tla-buildpackage
Title: Debian tla-buildpackage Manual
Author: <insert document author here>
Abstract: This manual describes what tla-buildpackage is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tla-buildpackage/tla-buildpackage.sgml.gz

Format: postscript
Files: /usr/share/doc/tla-buildpackage/tla-buildpackage.ps.gz

Format: text
Files: /usr/share/doc/tla-buildpackage/tla-buildpackage.text.gz

Format: HTML
Index: /usr/share/doc/tla-buildpackage/html/index.html
Files: /usr/share/doc/tla-buildpackage/html/*.html

  
